- hosts: "{{ variable_host | default('172.19.5.12') }}"
  
  remote_user: centos
  become: yes
  become_user: root

  tasks:
    - name: install nginx
      yum: name=nginx state=present

    - name: test command
      command: hostname
